# arxivの学問領域の指定
subject: "cat:cs.* OR cat:eess.* cat:stat.*"

# 検索キーワード
keywords:
  Federated Learning: 3
  Federated: 3
  Split Learning: 3
  Network: 1
  Heterogeneous: 1
  Migration: 1
# 通知の閾値
score_threshold: 3
