# arxivの学問領域の指定
subject: "cat:cs.* OR cat:eess.* cat:stat.*"

# 検索キーワード
keywords:
  Federated Learning: 3
  Federated: 3
  Split Learning: 3
  SplitNN: 3
  Network: 2
  Heterogeneous: 2
# 通知の閾値
score_threshold: 3
